version: '3'

services:
  ethereum:
    build:
      context: .
      dockerfile: ./ethereum/Dockerfile
    ports:
      - "8545:8545"

  contract_deployer:
    build:
      context: ./solidity
      dockerfile: ./Dockerfile
#    depends_on:
#      - ethereum
#      - gravity0

  raftleveldb:
    image: harbor.oneitfarm.com/itfarm-test/sal20000ad4588ae210303eaeipha2i4:0.0.1
    hostname: raftleveldb_dev
    container_name: raftleveldb_dev
    ports:
      - 5001:80

  ci0:
    image: cichain:v0.0.1
    #    image: harbor.oneitfarm.com/itfarm-test/sal20000ad4588ae210312eaeknb271z:v.1.3.24
    container_name: ci0
    hostname: ci0
    depends_on:
      - raftleveldb
    environment:
      CI_CHAIN_ID: ci0
      CI_NODE_DOMAIN: localhost
      CI_STATEDB_HOST: raftleveldb_dev
      CI_STATEDB_PORT: 80
      CI_STATEDB_TLS: "false"
      CI_HOME: /root/cid
      CI_TOKENNAME: stake
      #      IDG_APPID: abcdefg  # 设置之后 使用 中台log 输出到redis
      #      CI_CLIHOME: /root/cli
      CI_VALIDATOR_KEY: 4wttMiieaewLiRYu+y05j0uslBDOX5IA3k4TY9GtQzSdTcXyd5Y982Q3CUdh+h1XcCvtpIUb+5q6rtJ8W4SEFw==
      CI_PUBKEY: nU3F8neWPfNkNwlHYfodV3Ar7aSFG/uauq7SfFuEhBc=
    ports:
      - 26606:26656
      - 26557:26657
      - 1310:80
      - 1311:81

#  gravity0:
#    build:
#      context: ./module
#      dockerfile: ./Dockerfile
#    volumes:
#      - ./testdata/testchain/gravity0:/root/home
#    depends_on:
#      - ethereum
#    ports:
#      - "26656:26656"
#      - "26657:26657"
#      - "1317:1317"
#      - "9090:9090"
#      - "6060-6065:6060-6065"
#
#  orchestrator0:
#    build:
#      context: ./orchestrator
#      dockerfile: ./Dockerfile
#    depends_on:
#      - ethereum
#      - gravity0
#    environment:
#      - COSMOS_KEY=${COSMOS_KEY}
#      - COSMOS_PHRASE=${COSMOS_PHRASE}
#      - ETH_PRIVATE_KEY=${ETH_PRIVATE_KEY}
#      - VALIDATOR=${VALIDATOR}
#      - DENOM=${DENOM}
#      - CONTRACT_ADDR=${CONTRACT_ADDR}
#      - RUST_BACKTRACE=1
#
#  gravity1:
#    build:
#      context: ./module
#      dockerfile: ./Dockerfile
#    volumes:
#      - ./testdata/testchain/gravity1:/root/home
#    depends_on:
#      - ethereum
#      - gravity0
#
#  orchestrator1:
#    build:
#      context: ./orchestrator
#      dockerfile: ./Dockerfile
#    depends_on:
#      - ethereum
#      - gravity1
#    environment:
#      - COSMOS_KEY=${COSMOS_KEY}
#      - COSMOS_PHRASE=${COSMOS_PHRASE}
#      - ETH_PRIVATE_KEY=${ETH_PRIVATE_KEY}
#      - VALIDATOR=${VALIDATOR}
#      - DENOM=${DENOM}
#      - CONTRACT_ADDR=${CONTRACT_ADDR}
#      - RUST_BACKTRACE=1
#
#  gravity2:
#    build:
#      context: ./module
#      dockerfile: ./Dockerfile
#    volumes:
#      - ./testdata/testchain/gravity2:/root/home
#    depends_on:
#      - ethereum
#      - gravity0
#
#  orchestrator2:
#    build:
#      context: ./orchestrator
#      dockerfile: ./Dockerfile
#    depends_on:
#      - ethereum
#      - gravity2
#    environment:
#      - COSMOS_KEY=${COSMOS_KEY}
#      - COSMOS_PHRASE=${COSMOS_PHRASE}
#      - ETH_PRIVATE_KEY=${ETH_PRIVATE_KEY}
#      - VALIDATOR=${VALIDATOR}
#      - DENOM=${DENOM}
#      - CONTRACT_ADDR=${CONTRACT_ADDR}
#      - RUST_BACKTRACE=1
#
#  gravity3:
#    build:
#      context: ./module
#      dockerfile: ./Dockerfile
#    volumes:
#      - ./testdata/testchain/gravity3:/root/home
#    depends_on:
#      - ethereum
#      - gravity0
#
#  orchestrator3:
#    build:
#      context: ./orchestrator
#      dockerfile: ./Dockerfile
#    depends_on:
#      - ethereum
#      - gravity3
#    environment:
#      - COSMOS_KEY=${COSMOS_KEY}
#      - COSMOS_PHRASE=${COSMOS_PHRASE}
#      - ETH_PRIVATE_KEY=${ETH_PRIVATE_KEY}
#      - VALIDATOR=${VALIDATOR}
#      - DENOM=${DENOM}
#      - CONTRACT_ADDR=${CONTRACT_ADDR}
#      - RUST_BACKTRACE=1
