FROM harbor.oneitfarm.com/zhirenyun/go:1.13.15

WORKDIR /opt/ci123chain

COPY . /opt/ci123chain/
RUN cp -r ssh/* ~/.ssh/ & chmod 600 ~/.ssh/id_ras
RUN go env -w GO111MODULE=on && go env -w GOPRIVATE=gitlab.oneitfarm.com/bifrost/cilog && go env -w GOPROXY=https://goproxy.cn,direct && git config --global url."git@gitlab.oneitfarm.com:".insteadOf "https://gitlab.oneitfarm.com/"

RUN GOPROXY=https://goproxy.cn,direct GOSUMDB=off go build -o /opt/cid-linux ./cmd/cid
RUN GOPROXY=https://goproxy.cn,direct GOSUMDB=off go build -o /opt/cli-linux ./cmd/cicli
RUN GOPROXY=https://goproxy.cn,direct GOSUMDB=off go build -o /opt/cproxy-linux ./cmd/gateway

FROM harbor.oneitfarm.com/zhirenyun/baseimage:bionic-1.0.0

COPY --from=0 /opt/cid-linux /opt/cid-linux
COPY --from=0 /opt/cli-linux /opt/cli-linux
COPY --from=0 /opt/cproxy-linux /opt/cproxy-linux

COPY --from=0 /go/pkg/mod/github.com/wasmerio /go/pkg/mod/github.com/wasmerio

ENV GOPATH /go

COPY ./docker/node/2start.sh /etc/service/ci123chain/run

WORKDIR /opt
RUN chmod +x /etc/service/ci123chain/run