FROM harbor.oneitfarm.com/zhirenyun/go:1.15.6

WORKDIR /opt/ci123chain

COPY . /opt/ci123chain/
RUN go env -w GO111MODULE=on && \
  go env -w GOPROXY=https://goproxy.oneitfarm.com,https://goproxy.cn,direct && \
  go env -w GONOSUMDB=gitlab.oneitfarm.com/*

RUN go build -o /opt/cid-linux ./cmd/cid
RUN cd ./cmd/upgrade && go build -o /opt/upgrade .

FROM harbor.oneitfarm.com/zhirenyun/baseimage:bionic-1.0.0

COPY --from=0 /opt/cid-linux /opt/cid-linux
COPY --from=0 /opt/upgrade /opt/upgrade


COPY --from=0 /go/pkg/mod/github.com/ci123chain/wasmer-go@v1.0.3-rc2 /go/pkg/mod/github.com/ci123chain/wasmer-go@v1.0.3-rc2


ENV GOPATH /go
ENV DAEMON_NAME cid-linux

COPY ./docker/node/start-cid.sh /etc/service/cid/run
COPY ./jq-linux64 /usr/bin/jq
COPY ./serve_linux_amd64 /usr/bin/file_server
RUN chmod +x /usr/bin/jq
RUN chmod +x /usr/bin/file_server

WORKDIR /opt
RUN chmod +x /etc/service/cid/run
