FROM golang:1.15

WORKDIR /opt/ci123chain

COPY . /opt/ci123chain/
RUN go env -w GO111MODULE=on && \
  go env -w GOPROXY=https://goproxy.oneitfarm.com,https://goproxy.cn,direct && \
  go env -w GONOSUMDB=gitlab.oneitfarm.com/*

RUN go build -o /opt/cid-linux ./cmd/cid
RUN go build -o /opt/cproxy-linux ./cmd/gateway

FROM ubuntu:18.04

COPY --from=0 /opt/cid-linux /opt/cid-linux
COPY --from=0 /opt/cproxy-linux /opt/cproxy-linux


COPY --from=0 /go/pkg/mod/github.com/ci123chain/wasmer-go@v1.0.3-rc2 /go/pkg/mod/github.com/ci123chain/wasmer-go@v1.0.3-rc2


ENV GOPATH /go

COPY ./docker/node/2start.sh /opt/start.sh
COPY ./docker/node/exportFile.json /opt/exportFile.json

COPY ./jq-linux64 /usr/bin/jq
RUN chmod +x /usr/bin/jq

WORKDIR /opt
RUN chmod +x /opt/start.sh
CMD ./start.sh