version: '2'

networks:
    prom:

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        restart: always
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        networks:
            - prom

    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        restart: always
        volumes:
            - ./grafana-storage:/var/lib/grafana
        ports:
            - "3000:3000"
        networks:
            - prom
