global:
  scrape_interval:     30s
  evaluation_interval: 30s
 
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus
 
  - job_name: ci123chain
    static_configs:
      - targets: ['192.168.2.89:26660']
        labels:
          instance: ci123chain
