apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
        - name: couchdb
          image: couchdb:2.3.1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5984
