apiVersion: apps/v1
kind: Deployment
metadata:
  name: chain-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chain-gateway

  template:
    metadata:
      labels:
        app: chain-gateway
    spec:
      containers:
      - name: chain-gateway
        image: lbservice:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: chain-gateway
spec:
  type: NodePort
  ports:
  - port: 3030
    targetPort: 3030
    nodePort: 30303
  selector:
    app: chain-gateway
