version: "3"
services:
  ci0:
    image: cichain:v0.0.1
    container_name: ci0
    hostname: ci0
    environment:
      ShardID: ci0
    ports:
      - 26606:26656
      - 1310:80
    volumes:
      - ./node0:/root/cid
#    depends_on:
#      - couchdb_service
    networks:
      testdocker_couchDB:

  ci1:
    image: cichain:v0.0.1
    container_name: ci1
    hostname: ci1
    environment:
      ShardID: ci1
    ports:
      - 26616:26656
      - 1311:80
    volumes:
      - ./node1:/root/cid
    # depends_on:
    #   - ci0
    #   - couchdb_service
    networks:
      testdocker_couchDB:

  ci2:
    image: cichain:v0.0.1
    container_name: ci2
    hostname: ci2
    environment:
      ShardID: ci2
    ports:
      - 26626:26656
      - 1312:80
    volumes:
      - ./node2:/root/cid
    # depends_on:
    #   - ci0
    #   - couchdb_service
    networks:
      testdocker_couchDB:

  gateway:
    image: cichain:v0.0.1
    container_name: gatewayservice
    hostname: gatewayservice
    volumes:
    - ./gateway:/root/gateway
    environment:
      GATEWAY: "true"
    ports:
      - 3030:3030
    networks:
      testdocker_couchDB:

#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    hostname: prometheus
#    restart: always
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - 9090:9090
#    networks:
#      testdocker_couchDB:
#
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    hostname: grafana
#    restart: always
#    volumes:
#      - ./grafana-storage:/var/lib/grafana
#    ports:
#      - 3000:3000
#    networks:
#      testdocker_couchDB:

networks: ##定义网络组
  testdocker_couchDB: ## 网络组名称
    external: true