version: "3"
services:
  ci1:
    image: cichain:v0.0.1
    container_name: ci1
    hostname: ci1
    environment:
      ShardID: ci1
    ports:
      - 26616:26656
      - 1311:80
    volumes:
      - ./node1:/root/cid
    # depends_on:
    #   - ci0
    #   - couchdb-service
    networks:
      testdocker_couchDB:

  ci2:
    image: cichain:v0.0.1
    container_name: ci2
    hostname: ci2
    environment:
      ShardID: ci2
    ports:
      - 26626:26656
      - 1312:80
    volumes:
      - ./node2:/root/cid
    # depends_on:
    #   - ci0
    #   - couchdb-service
    networks:
      testdocker_couchDB:

networks: ##定义网络组
  testdocker_couchDB: ## 网络组名称
   external: true